Repository Cocktail-Shop/backend, pull requests merged in 2022-08, with the labels that each got.

#14 칵테일 상품 등록 및 조회 구현
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CocktailService.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
Labels: 신규 개발, Admin - 상품, Test

#15 Edit: git 충돌 에러 해결
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/CartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/CartItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CocktailService.kt
Labels: 이슈 처리

#18 Feature/login - Feat : 로그인, 회원가입 구현
  C-Shop/build.gradle.kts
  C-Shop/src/main/kotlin/com/lionTF/CShop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/dto/AuthMemberDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/dto/RequestSignUpDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/dto/ResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/MemberRole.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberDetailsService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Cart.kt
  C-Shop/src/main/resources/templates/success.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MemberTests.kt
Labels: Member - 회원, 신규 개발

#21 Refactor: Member 엔티티 초기화 작업 및 회원 삭제 기능 추가
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/Member.kt
Labels: 신규 개발, Admin - 회원, Refactoring

#25 Admin 기능 추가 및 test code 작성
  C-Shop/src/main/kotlin/com/lionTF/CShop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminMemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminMemberRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminMemberRepositoryCustomImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 신규 개발, Admin - 주문 관리, Admin - 회원, Admin - 상품, Test, Refactoring

#28 상품 조회 기능 구현했습니다.
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ResponseAllOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ResponseItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/image/service/AuthService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/image/service/ObjectService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminMemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminOrderRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminMemberRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminMemberRepositoryCustomImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminMemberRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 신규 개발, Admin - 주문 관리, Admin - 회원, Test, Refactoring, Back-end

#30 Feature/members my page : Feat - 마이페이지 관련 API 구현 및 mockuser를 이용한 테스트코드 작성
  C-Shop/src/main/kotlin/com/lionTF/CShop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/MyPageDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/RequestSignUpDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberService.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MemberTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MyPageTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/WithMockCustomUser.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/WithMockCustomUserSecurityContextFactory.kt
Labels: Member - 회원, Member - 마이페이지, 신규 개발, 기능 수정, Back-end

#34 Shop kyungjun
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/PageController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/AddCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/PageRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/PageResultDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/repository/CocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/repository/ItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CartItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/OrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/PageSerivce.kt
Labels: Shopping Mall - 장바구니, 신규 개발, Shopping Mall - 상품, Back-end

#38 상품, 회원 주문 조회 페이지 구현
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMainController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindCocktails.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindOrders.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Category.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminCocktailRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminCocktailRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminItemRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminItemRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/createItemForm.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/main.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 신규 개발, 기능 수정, Admin - 주문 관리, Admin - 회원, Admin - 상품, Back-end, Front-end

#40 Shop kyungjun
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/CocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/PageController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/SearchController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/PageRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/ItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/PageSerivce.kt
  C-Shop/src/main/resources/static/images/shop/products/cocktail-1.jpg
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: 신규 개발, Shopping Mall - 상품, Front-end

#43 Admin 기능 중 삭제 관련 추가 기능 구현했습니다.
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 신규 개발, Admin - 주문 관리, Admin - 회원, Admin - 상품, Test, Back-end, 기능 추가

#44 Feature/members view
  C-Shop/src/main/kotlin/com/lionTF/CShop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/IdInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/MyPageDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/RequestPasswordInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/RequestSignUpDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/ResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberService.kt
  C-Shop/src/main/resources/static/js/login-script.js
  C-Shop/src/main/resources/templates/global/headData.html
  C-Shop/src/main/resources/templates/global/header.html
  C-Shop/src/main/resources/templates/global/message.html
  C-Shop/src/main/resources/templates/global/scriptData.html
  C-Shop/src/main/resources/templates/members/forget-id-result.html
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/forget-password.html
  C-Shop/src/main/resources/templates/members/index.html
  C-Shop/src/main/resources/templates/members/login.html
  C-Shop/src/main/resources/templates/members/my-page.html
  C-Shop/src/main/resources/templates/members/reassign-forget-password.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MemberTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MyPageTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/WithMockCustomUserSecurityContextFactory.kt
Labels: 신규 개발, 기능 수정, Test, Back-end, Front-end

#46 삭제 관련 기능 추가했습니다.
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindCocktails.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminCocktailRepositoryImpl.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/main.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
Labels: 신규 개발, Admin - 주문 관리, Admin - 회원, Admin - 상품, Front-end, 기능 추가

#47 정적 팩토리 패턴으로 리펙토링 및 기능 추가하였습니다!
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindOrders.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/RequestCreateItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ResponseItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminOrderItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/OrderItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 기능 수정, Admin - 주문 관리, Admin - 회원, Admin - 상품, Refactoring, Back-end, Front-end

#49 Shop kyungjun
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/AddressDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/CocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/PageController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/SearchController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/AddCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/ItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/PageResultDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/SearchCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/SearchItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailItemInfoDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/CartItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/OrderItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/repository/CartRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/repository/CocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/repository/ItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/ItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/PageSerivceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/shopinterface/CartItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/shopinterface/CocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/shopinterface/ItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/shopinterface/OrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/shopinterface/PageSerivce.kt
  C-Shop/src/main/resources/templates/global/AlcoholHeader.html
  C-Shop/src/main/resources/templates/global/NonAlcoholHeader.html
  C-Shop/src/main/resources/templates/global/header.html
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Shopping Mall - 상품, Refactoring, Back-end

#50 Feature/email : Feat,Edit - email 컬럼추가 및 이메일을 통한 임시 비밀번호 발급 구현
  C-Shop/build.gradle.kts
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/MailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/RequestPasswordInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/RequestSignUpDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberService.kt
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/forget-password.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MemberTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/WithMockCustomUserSecurityContextFactory.kt
Labels: Member - 회원, 신규 개발, Back-end

#53 정적 팩토리 패턴으로 코드 리펙토링하여 test code또한 리펙토링하였습니다.
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/CreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/DeleteOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindCocktails.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindCocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/RequestCreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ResponseCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/ResponseItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminCocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminCocktailRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminCocktailRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminItemRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminItemRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/OrderItem.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/cocktail/updateCocktailForm.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: Admin - 주문 관리, Admin - 회원, Admin - 상품, Test, Refactoring, Back-end, 기능 추가

#54 Feature/redis: Feat - Redis를 이용한 session 처리 + 회원가입및 로그인시 이메일인증
  C-Shop/build.gradle.kts
  C-Shop/src/main/kotlin/com/lionTF/CShop/CShopApplication.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/AuthNumberDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/IdInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/controller/dto/MailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/member/service/MemberService.kt
  C-Shop/src/main/resources/static/js/login-script.js
  C-Shop/src/main/resources/templates/global/scriptData.html
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/MemberTests.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/member/security/WithMockCustomUserSecurityContextFactory.kt
Labels: Member - 회원, Back-end, 기능 추가

#60 Shop kyungjun
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/ItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/SearchCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/SearchItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/controller/dto/cocktailItemInfoDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/CartItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/OrderItem.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/CocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/ItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/service/PageSerivceImpl.kt
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Shopping Mall - 상품, Back-end, Front-end

#59 배달 로직 관련 추가 기능 구현했습니다.
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/controller/dto/FindOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/DeliveryStatus.kt
  C-Shop/src/main/kotlin/com/lionTF/CShop/domain/shop/models/Orders.kt
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/models/CocktailUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/models/ItemUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/CShop/domain/admin/service/AdminOrderServiceTest.kt
Labels: Shopping Mall - 주문, 신규 개발, Test, Back-end, 기능 추가

#61 package 이름 변경했습니다
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindCocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminMemberRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AuthService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageService.kt
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
Labels: Refactoring, Back-end

#65 프론트 에러 수정
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/ItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/MemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/OrderItemRepository.kt
  C-Shop/src/main/resources/templates/members/forget-id-result.html
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/forget-password.html
  C-Shop/src/main/resources/templates/members/login.html
  C-Shop/src/main/resources/templates/members/my-page.html
  C-Shop/src/main/resources/templates/members/reassign-forget-password.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Hotfix, Front-end

#66 프론트 에러 수정
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/ItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/MemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/OrderItemRepository.kt
  C-Shop/src/main/resources/templates/members/forget-id-result.html
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/forget-password.html
  C-Shop/src/main/resources/templates/members/login.html
  C-Shop/src/main/resources/templates/members/my-page.html
  C-Shop/src/main/resources/templates/members/reassign-forget-password.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Hotfix, Front-end

#67 Fix : html 오타 수정
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Hotfix, Front-end

#68 Fix : html 오타 수정
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Hotfix, Front-end

#69 Refactor: 코드 리뷰 적용
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/PageController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/SearchController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/CartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/CartResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/DeleteCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/FindCartDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/ItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/OrderItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/OrderResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/PageRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/PageResultDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/SearchCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/SearchItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/cocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/cocktailItemInfoDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/Cart.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/CartItem.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/DeliveryStatus.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/OrderItem.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/OrderStatus.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/Orders.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/ItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/MemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/OrderItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/OrderRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/SearchRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/SearchRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/ItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/PageSerivceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/PageServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/CartItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/CocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/ItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/OrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/PageSerivce.kt
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, Shopping Mall - 상품, Refactoring, Back-end

#70 칵테일, 상품 이미지 수정 삭제 로직 구현했습니다
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMainController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindCocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/FindOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/RequestCreateCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/RequestCreateItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ResponseCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ResponseItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Category.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminCocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminCocktailRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminMemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminOrderItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminOrderRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminCocktailRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminCocktailRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminItemRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminItemRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminMemberRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminMemberRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminCocktailItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/ImageService.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/cocktail/updateCocktailForm.html
  C-Shop/src/main/resources/templates/admins/item/createItemForm.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/main.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
Labels: 신규 개발, Admin - 상품, Back-end, Front-end

#71 칵테일 주문 프론트 구현, 의미 없는 코드 제거
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Shopping Mall - 주문, 기능 수정, Refactoring, Front-end

#74 Feature/social login : Feat,Edit - 소셜로그인 추가, 접근제어 추가
  C-Shop/build.gradle.kts
  C-Shop/src/main/kotlin/com/lionTF/cshop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/AuthMemberDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/RequestPreMemberInfoDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/ResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/handler/CustomAccessDeniedHandler.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/models/MemberRole.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/OAuth2UserDetailsService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/memberinterface/MemberService.kt
  C-Shop/src/main/resources/static/js/login-script.js
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/login.html
  C-Shop/src/main/resources/templates/members/pre-member-page.html
  C-Shop/src/main/resources/templates/members/social-my-page.html
Labels: Member - 회원, 기능 수정, Back-end, 기능 추가

#76 배달 상태 관련 백엔드 프론트 구현했습니다.
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMainController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/DeliveryStatus.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/Orders.kt
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/models/CocktailUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/models/ItemUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/member/security/MemberTests.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/shop/models/OrdersUnitTest.kt
Labels: Admin - 주문 관리, Test, Back-end, Front-end, 기능 추가

#78 페이지에 들어가는 아이템 수 변경
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/PageRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/PageResultDTO.kt
Labels: 기능 수정, Shopping Mall - 상품, Back-end

#80 HotFix: imageServiceimpl main 함수 주석처리
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageServiceImpl.kt
Labels: Hotfix, Back-end

#81 배포v0.3
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageServiceImpl.kt
Labels: Hotfix, 배포

#82 프론트 이미지 가져오기 코드 수정
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, Shopping Mall - 상품, Front-end

#83 프론트 이미지 가져오기 코드 수정
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, Shopping Mall - 상품, Front-end

#85 Feature/admin main :Refactoring
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMainController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailCreateRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemCreateRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/MembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminOrderItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminCocktailRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminCocktailRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminItemRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminItemRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminMemberRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminMemberRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/models/CocktailUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/models/ItemUnitTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceTest.kt
Labels: 기능 수정, Refactoring, Back-end

#87 Shop kyungjun
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/OrderItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/resources/templates/global/NonAlcoholHeader.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, 기능 수정, Shopping Mall - 상품, Back-end, Front-end, 기능 추가

#89 Refactoring/members : Refactoring, Feat - 코드리뷰 반영한 리팩토링 진행 및 카카오 소셜로그인 구현 및 예외처리
  C-Shop/src/main/kotlin/com/lionTF/cshop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/PreMemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/AddressDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/AuthMemberDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/AuthNumberDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/IdInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MemberResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MyPageDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/PasswordInquiryRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/PreMemberInfoRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/RequestPasswordInquiryDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/RequestPreMemberInfoDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/RequestSignUpDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/ResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/SignUpRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/handler/CustomAccessDeniedHandler.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/handler/OAuthFailureHandler.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/models/Member.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/models/MemberRole.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MailAuthServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MemberDetailsService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MyPageServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/OAuth2UserDetailsService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/memberinterface/MailAuthService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/memberinterface/MemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/memberinterface/MyPageService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/Cart.kt
  C-Shop/src/main/resources/static/js/login-script.js
  C-Shop/src/main/resources/templates/global/headData.html
  C-Shop/src/main/resources/templates/global/header.html
  C-Shop/src/main/resources/templates/global/message.html
  C-Shop/src/main/resources/templates/global/scriptData.html
  C-Shop/src/main/resources/templates/members/forget-id-result.html
  C-Shop/src/main/resources/templates/members/forget-id.html
  C-Shop/src/main/resources/templates/members/forget-password.html
  C-Shop/src/main/resources/templates/members/index.html
  C-Shop/src/main/resources/templates/members/login.html
  C-Shop/src/main/resources/templates/members/my-page.html
  C-Shop/src/main/resources/templates/members/pre-member-page.html
  C-Shop/src/main/resources/templates/members/reassign-password.html
  C-Shop/src/main/resources/templates/members/signup.html
  C-Shop/src/main/resources/templates/members/social-my-page.html
  C-Shop/src/main/resources/templates/success.html
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/member/security/MyPageTests.kt
Labels: Member - 회원, Member - 마이페이지, Refactoring, 기능 추가

#91 Feature/wish list : 찜하기 추가 기능 BE,FE 구현했습니다.
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMainController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminMembersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminOrdersController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteMembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/DeleteOrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminMemberRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/ImageServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminCocktailService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminMemberService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminOrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/ImageService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/WishListController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/WishListDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/WishList.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/WishListRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/WishListServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/WishListService.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/cocktail/updateCocktailForm.html
  C-Shop/src/main/resources/templates/admins/item/createItemForm.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/main.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/main/resources/templates/global/AlcoholHeader.html
  C-Shop/src/main/resources/templates/global/NonAlcoholHeader.html
  C-Shop/src/main/resources/templates/global/header.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
  C-Shop/src/main/resources/templates/shop/wishList.html
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/shop/service/WishListServiceTest.kt
Labels: 기능 수정, Test, Refactoring, Back-end, Front-end, 기능 추가, Shopping Mall - 찜하기

#92 Feat, Fix : cart, orders FE 구현 및 기능 수정
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/FindCartDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/OrderItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/OrderService.kt
  C-Shop/src/main/resources/templates/global/AlcoholHeader.html
  C-Shop/src/main/resources/templates/global/NonAlcoholHeader.html
  C-Shop/src/main/resources/templates/global/header.html
  C-Shop/src/main/resources/templates/shop/cart.html
  C-Shop/src/main/resources/templates/shop/orderList.html
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, 신규 개발, 기능 수정, Back-end, Front-end

#96 Refactoring/admin: Refactoring
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemCreateRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/MembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MyPageDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/WishListController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/WishList.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/WishListServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/WishListService.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceTest.kt
Labels: Refactoring, Back-end

#97 Fix, Refactoring : 장바구니, 주문 FE 연결, 리팩토링
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/CartResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/DeleteCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/FindCartDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/CartItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/OrderService.kt
  C-Shop/src/main/resources/templates/shop/cart.html
Labels: Shopping Mall - 주문, Shopping Mall - 장바구니, 기능 수정, Refactoring, Back-end, Front-end

#98 배포V0.9
  C-Shop/src/main/kotlin/com/lionTF/cshop/config/SecurityConfig.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/CocktailsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemCreateRequestDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/ItemsDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/MembersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Cocktail.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/CocktailItem.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/models/Item.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/MemberController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MemberResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MyPageDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CartItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/CocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/ItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/WishListController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartCocktailItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/AddCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/CartResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/DeleteCartItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/FindCartDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/OrdersDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/RequestOrderDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/SearchCocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/SearchItemDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/cocktailDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/WishList.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/CartItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryCustom.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/custom/CartRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CartItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/ItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/WishListServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/CartItemService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/OrderService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/PageService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/WishListService.kt
  C-Shop/src/main/resources/templates/members/my-page.html
  C-Shop/src/main/resources/templates/shop/cart.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminCocktailServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminOrderServiceTest.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/member/security/WithMockCustomUserSecurityContextFactory.kt
Labels: 배포

#99 Fix: 칵테일 등록 시 아이템이 20개만 보이는 에러 수정
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminCocktailController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/AdminItemController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/admininterface/AdminItemService.kt
  C-Shop/src/test/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceTest.kt
Labels: 기능 수정, Admin - 상품, Back-end, 배포

#102 배포 v1.1
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/updateCocktailForm.html
Labels: 배포

#103 배포 v1.2
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/OrderController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/controller/dto/CartResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/OrderServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/OrderService.kt
Labels: 배포

#108 배포V1.5
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/WishListRepository.kt
Labels: 기능 수정, Back-end, 배포

#112 Fix : 칵테일 Form 검사시 빈 DTO 값 가져오는 에러 수정 및 수량보다 작을때가 아닌 수량과 작거나 같을때로 조건 수정
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Hotfix

#111 Origin/fix/input : QA 이슈 처리
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/controller/dto/AdminResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/models/WishList.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/repository/WishListRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/WishListServiceImpl.kt
  C-Shop/src/main/resources/static/plugins/bootstrap/css/bootstrap.min.css
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/item/createItemForm.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/main/resources/templates/shop/orderList.html
  C-Shop/src/main/resources/templates/shop/wishList.html
Labels: 이슈 처리, Back-end, Front-end

#114 마지막으로 가기 페이지 처리 오류 수정, 정렬 기준 오름차순으로 변경
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/PageServiceImpl.kt
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
Labels: 이슈 처리, Front-end

#115 Fix: 주류, 칵테일, 비주류 조회시 화면 깨지는 현상 해결 및 회원 삭제 시 주문 목록에도 보이게 수정했습니다.
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/resources/templates/shop/shopAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopCocktail.html
  C-Shop/src/main/resources/templates/shop/shopNonAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchAlcohol.html
  C-Shop/src/main/resources/templates/shop/shopSearchCocktail.html
  C-Shop/src/main/resources/templates/shop/shopSearchNonAlcohol.html
Labels: 이슈 처리, Admin - 주문 관리, Shopping Mall - 상품, Back-end, Front-end

#116 Fix/members : Fix - 백엔드 관련 QA 요청사항 반영
  C-Shop/build.gradle.kts
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminMemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/controller/dto/MemberResponseDTO.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/repository/MemberAuthRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/MemberServiceImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/member/service/OAuth2UserDetailsService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/global/controller/BasicErrorController.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/global/controller/dto/ErrorMessageDTO.kt
  C-Shop/src/main/resources/templates/global/BasicError.html
Labels: Hotfix, Member - 회원, Admin - 회원, Back-end

#117 Refactor: admin 조회 모든 페이지 상품명을 보여주는 곳에서 보여지는 상품명 길이 20 글자 제한으로 변경하였습니다.
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminCocktailItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/AdminItemRepository.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/repository/custom/AdminOrderRepositoryImpl.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/admin/service/AdminItemServiceImpl.kt
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
Labels: 이슈 처리, Admin - 주문 관리, Admin - 상품, Front-end

#118 Fix/soldout
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
  C-Shop/src/main/resources/templates/shop/singleItem.html
Labels: Front-end

#120 Fix: 함수 파라미터 이름 변경
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/CocktailWishListService.kt
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/shopinterface/ItemWishListService.kt
Labels: Hotfix, Back-end, 배포

#123 Fix : 칵테일 재료는 0 허용하게 수정
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
Labels: Front-end

#124 배포v2.0
  C-Shop/src/main/resources/templates/admins/cocktail/createCocktailForm.html
  C-Shop/src/main/resources/templates/admins/cocktail/getAllCocktail.html
  C-Shop/src/main/resources/templates/admins/cocktail/getCocktailsByName.html
  C-Shop/src/main/resources/templates/admins/cocktail/updateCocktailForm.html
  C-Shop/src/main/resources/templates/admins/item/createItemForm.html
  C-Shop/src/main/resources/templates/admins/item/getAllItem.html
  C-Shop/src/main/resources/templates/admins/item/getItemsByName.html
  C-Shop/src/main/resources/templates/admins/item/updateItemForm.html
  C-Shop/src/main/resources/templates/admins/member/getAllMember.html
  C-Shop/src/main/resources/templates/admins/member/getSearchMember.html
  C-Shop/src/main/resources/templates/admins/order/getAllOrder.html
  C-Shop/src/main/resources/templates/admins/order/getMemberOrder.html
  C-Shop/src/main/resources/templates/shop/singleCocktail.html
Labels: Hotfix, 배포

#125 Fix : 재고 수량과 요청 수량이 같을 때 장바구니에 안담기는 오류 수정
  C-Shop/src/main/kotlin/com/lionTF/cshop/domain/shop/service/CartItemServiceImpl.kt
Labels: Hotfix, Shopping Mall - 장바구니, Back-end
